### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by aikrq** [SectionTN/otp-input#1]
Can you add some screenshots in readme?

**Comment by SectionTN** [comment]
hello, sorry for the inconvenience. yes i'm working on an example project of the library and i will add screenshots soon. stay tuned

**Comment by SectionTN** [comment]
hello again, @remaker17 
i've add an `react-native-cli` example and a `snack` demo 
see them in readme file
i'll add screenshots tomorrow with some videos
